qtbase: don't enable renameat2 by default
* do_configure fails when renameat2 is enabled:
  ERROR: Feature 'renameat2' was enabled, but the pre-condition 'config.linux && tests.renameat2' failed.

Checking for renameat2()...
+ cd /OE/build/oe-core/tmp-glibc/work/core2-64-oe-linux/qtbase/5.10.1+gitAUTOINC+6c6ace9d23-r0/build/config.tests/renameat2 && PKG_CONFIG_SYSROOT_DIR=/OE/build/oe-core/tmp-glibc/work/core2-64-oe-linux/qtbase/5.10.1+gitAUTOINC+6c6ace9d23-r0/recipe-sysroot PKG_CONFIG_LIBDIR=/OE/build/oe-core/tmp-glibc/work/core2-64-oe-linux/qtbase/5.10.1+gitAUTOINC+6c6ace9d23-r0/recipe-sysroot/usr/lib/pkgconfig /OE/build/oe-core/tmp-glibc/work/core2-64-oe-linux/qtbase/5.10.1+gitAUTOINC+6c6ace9d23-r0/recipe-sysroot-native/usr/bin/qt5/qmake -qtconf /OE/build/oe-core/tmp-glibc/work/core2-64-oe-linux/qtbase/5.10.1+gitAUTOINC+6c6ace9d23-r0/build/bin/qt.conf "CONFIG -= qt debug_and_release app_bundle lib_bundle" "CONFIG += shared use_gold_linker warn_off console single_arch" "QMAKE_CFLAGS += --sysroot=/OE/build/oe-core/tmp-glibc/work/core2-64-oe-linux/qtbase/5.10.1+gitAUTOINC+6c6ace9d23-r0/recipe-sysroot" "QMAKE_CXXFLAGS += --sysroot=/OE/build/oe-core/tmp-glibc/work/core2-64-oe-linux/qtbase/5.10.1+gitAUTOINC+6c6ace9d23-r0/recipe-sysroot" "QMAKE_LFLAGS += --sysroot=/OE/build/oe-core/tmp-glibc/work/core2-64-oe-linux/qtbase/5.10.1+gitAUTOINC+6c6ace9d23-r0/recipe-sysroot" -early "CONFIG += cross_compile" /OE/build/oe-core/tmp-glibc/work/core2-64-oe-linux/qtbase/5.10.1+gitAUTOINC+6c6ace9d23-r0/build/config.tests/renameat2
+ cd /OE/build/oe-core/tmp-glibc/work/core2-64-oe-linux/qtbase/5.10.1+gitAUTOINC+6c6ace9d23-r0/build/config.tests/renameat2 && MAKEFLAGS= make
> x86_64-oe-linux-g++  -m64 -march=core2 -mtune=core2 -msse3 -mfpmath=sse -fstack-protector-strong  -D_FORTIFY_SOURCE=2 -Wformat -Wformat-security -Werror=format-security --sysroot=/OE/build/oe-core/tmp-glibc/work/core2-64-oe-linux/qtbase/5.10.1+gitAUTOINC+6c6ace9d23-r0/recipe-sysroot -c -pipe  -O2 -pipe -g -feliminate-unused-debug-types -fdebug-prefix-map=/OE/build/oe-core/tmp-glibc/work/core2-64-oe-linux/qtbase/5.10.1+gitAUTOINC+6c6ace9d23-r0=/usr/src/debug/qtbase/5.10.1+gitAUTOINC+6c6ace9d23-r0 -fdebug-prefix-map=/OE/build/oe-core/tmp-glibc/work/core2-64-oe-linux/qtbase/5.10.1+gitAUTOINC+6c6ace9d23-r0/recipe-sysroot-native= -fdebug-prefix-map=/OE/build/oe-core/tmp-glibc/work/core2-64-oe-linux/qtbase/5.10.1+gitAUTOINC+6c6ace9d23-r0/recipe-sysroot=  -fvisibility-inlines-hidden --sysroot=/OE/build/oe-core/tmp-glibc/work/core2-64-oe-linux/qtbase/5.10.1+gitAUTOINC+6c6ace9d23-r0/recipe-sysroot --sysroot=/OE/build/oe-core/tmp-glibc/work/core2-64-oe-linux/qtbase/5.10.1+gitAUTOINC+6c6ace9d23-r0/recipe-sysroot -O2 -w -fPIC  -I. -I/OE/build/oe-core/tmp-glibc/work/core2-64-oe-linux/qtbase/5.10.1+gitAUTOINC+6c6ace9d23-r0/git/mkspecs/linux-oe-g++ -o main.o main.cpp
> main.cpp: In function 'int main(int, char**)':
> main.cpp:9:53: error: 'RENAME_NOREPLACE' was not declared in this scope
>      renameat2(AT_FDCWD, argv[1], AT_FDCWD, argv[2], RENAME_NOREPLACE | RENAME_WHITEOUT);
>                                                      ^~~~~~~~~~~~~~~~
> main.cpp:9:53: note: suggested alternative: '_IOS_NOREPLACE'
>      renameat2(AT_FDCWD, argv[1], AT_FDCWD, argv[2], RENAME_NOREPLACE | RENAME_WHITEOUT);
>                                                      ^~~~~~~~~~~~~~~~
>                                                      _IOS_NOREPLACE
> main.cpp:9:72: error: 'RENAME_WHITEOUT' was not declared in this scope
>      renameat2(AT_FDCWD, argv[1], AT_FDCWD, argv[2], RENAME_NOREPLACE | RENAME_WHITEOUT);
>                                                                         ^~~~~~~~~~~~~~~
> main.cpp:9:5: error: 'renameat2' was not declared in this scope
>      renameat2(AT_FDCWD, argv[1], AT_FDCWD, argv[2], RENAME_NOREPLACE | RENAME_WHITEOUT);
>      ^~~~~~~~~
> main.cpp:9:5: note: suggested alternative: 'renameat'
>      renameat2(AT_FDCWD, argv[1], AT_FDCWD, argv[2], RENAME_NOREPLACE | RENAME_WHITEOUT);
>      ^~~~~~~~~
>      renameat
> Makefile:174: recipe for target 'main.o' failed
> make: *** [main.o] Error 1
test config.corelib.tests.renameat2 FAILED

Signed-off-by: Martin Jansa <Martin.Jansa@gmail.com>